### ISSUE TITLE
Potential code typo

### ISSUE THREAD

**Issue by Strength-Ampersand-Honor** [causalityloop/theta_gn_containerized#3]
Should the minimal docker download code read as:

sudo apt install -y docker.io

instead of

sudo apt-install -y docker.io

Am working on a Raspberry Pi 4 Model B. Had to use the first line of code in order to download the docker pre-req. Is this an error with my software capabilities?

**Comment by causalityloop** [comment]
100% a typo. Thank you for catching this. I could have sworn I copy/pasted the commands correctly but obviously this slipped through. I will make this correction. Thank you again.

For the Raspberry PI, the instructions here will not be much of help to you as the binaries that are pulled in creating the docker are for amd64/mac. In building the docker, I am not creating any theta binaries, but pulling them down from the official theta, itself.

https://github.com/causalityloop/theta_gn_containerized/blob/main/docker/Dockerfile#L31

I was able to build the binaries for the Pi (arm)...but the Pi had issues finishing its initial chain sync.

It's been a couple months since I last tried and might be worth it again. I gave it a shot about 5-6 times before giving up. I'm convinced it is not a lack of speed issue - just that the GN gives up, after some time, and no longer tries syncing.

**Comment by Strength-Ampersand-Honor** [comment]
Thank you for getting back on this, and with such a detailed response.

Been exploring many different repositories and insights on connecting a Guardian Node to the network through a Raspberry Pi. Thought the software has received all of the necessary data, but continuing to receive an executive format error when attempting to launch.

A lot of data to process (quite new to this world). Will be able to give a more informed response in the near future.

**Comment by causalityloop** [comment]
You are welcome. Most likely the format error is running the executable for the wrong arch. ie. you are running amd64 prebuilt binary on the arm device (pi).

**Comment by Strength-Ampersand-Honor** [comment]
If I understand this correctly...wow! You were able to build the binaries for the Pi. Meaning, you were able to create the sequence of bits that connects the Raspberry Pi software to the Theta Guardian Node network? Wow, extremely impressive and thank you for sharing!

Okay okay, you're thinking that the Guardian Node(GN) quits attempting to sync with the binaries coming from the Raspberry? Agree with you that its not a lack of speed issue. Did you come up with a hypothesis, 5 or 6 months ago, as to why it may be giving up on our Raspberry Pi's?

The Raspberry Pi by default is an arm64 device, which should translate seamlessly with the commands from Techguyk:

<https://github.com/kuoyaoming93/guardian-mainnet-guide/blob/master/docs/COMPILE_ARM64.md#install-guardian-node-from-source-code>

As you mentioned, am probably running the executable for the wrong arch. You're 100% correct.

`@raspberrypi:~ $ arch ; uname -m
aarch64
aarch64
`
In order to change the arch type, would you download a new OS onto the SSD and start from scratch? #THETA

**Comment by causalityloop** [comment]
closing this issue as I have since fixed the type the issue was originally opened before

regarding building the Pi binaries: I used Techguyk's instructions to build the source and bundled it in a docker (didn't push to a branch here as I did not get it to work successfully when running). Everything builds fine ...just that the sync gives up after a period of time. I have not gone through the theta source to understand any better. The errors (too long to remember) I received were not too helpful to discern what was happening under the covers. I'm sure i'll take another crack at it this month.

For your last comment, it is based on the arch of the chip...you need an arm based OS. amd64 OS will not help here.
